// generators/app/templates/svelte/src/lib/DataverseAPIDemo.svelte
<script lang="ts">
    import { createEventDispatcher } from 'svelte';

    export let connection: ToolBoxAPI.DataverseConnection | null = null;

    const dispatch = createEventDispatcher<{
        log: { message: string; type?: 'info' | 'success' | 'warning' | 'error' };
    }>();

    let accountName = 'Sample Account';
    let createdAccountId: string | null = null;
    let queryOutput = '';
    let crudOutput = '';
    let metadataOutput = '';

    async function showNotification(title: string, body: string, type: 'success' | 'info' | 'warning' | 'error') {
        try {
            await window.toolboxAPI.utils.showNotification({ title, body, type, duration: 3000 });
        } catch (error) {
            console.error('Error showing notification:', error);
        }
    }

    async function queryAccounts() {
        if (!connection) {
            await showNotification('No Connection', 'Please connect to a Dataverse environment', 'warning');
            return;
        }

        try {
            queryOutput = 'Querying accounts...\n';

            const fetchXml = `
<fetch top="10">
  <entity name="account">
    <attribute name="name" />
    <attribute name="accountid" />
    <attribute name="emailaddress1" />
    <attribute name="telephone1" />
    <order attribute="name" />
  </entity>
</fetch>
            `.trim();

            const result = await window.dataverseAPI.fetchXmlQuery(fetchXml);

            let output = `Found ${result.value.length} account(s):\n\n`;
            result.value.forEach((account: any, index: number) => {
                output += `${index + 1}. ${account.name}\n`;
                output += `   ID: ${account.accountid}\n`;
                if (account.emailaddress1) output += `   Email: ${account.emailaddress1}\n`;
                if (account.telephone1) output += `   Phone: ${account.telephone1}\n`;
                output += '\n';
            });

            queryOutput = output;
            dispatch('log', { message: `Queried ${result.value.length} accounts`, type: 'success' });
        } catch (error) {
            queryOutput = `Error: ${(error as Error).message}`;
            dispatch('log', { message: `Error querying accounts: ${(error as Error).message}`, type: 'error' });
        }
    }

    async function createAccount() {
        if (!connection) {
            await showNotification('No Connection', 'Please connect to a Dataverse environment', 'warning');
            return;
        }

        try {
            crudOutput = 'Creating account...\n';

            const result = await window.dataverseAPI.create('account', {
                name: accountName,
                emailaddress1: 'sample@example.com',
                telephone1: '555-0100',
                description: 'Created by Svelte Sample Tool',
            });

            createdAccountId = result.id;
            crudOutput = `Account created successfully!\n\nID: ${result.id}\nName: ${accountName}\n`;

            await showNotification('Account Created', `Account "${accountName}" created successfully`, 'success');
            dispatch('log', { message: `Account created: ${result.id}`, type: 'success' });
        } catch (error) {
            crudOutput = `Error: ${(error as Error).message}`;
            dispatch('log', { message: `Error creating account: ${(error as Error).message}`, type: 'error' });
        }
    }

    async function updateAccount() {
        if (!createdAccountId) {
            await showNotification('No Account', 'Please create an account first', 'warning');
            return;
        }

        try {
            crudOutput = 'Updating account...\n';

            await window.dataverseAPI.update('account', createdAccountId, {
                description: 'Updated by Svelte Sample Tool at ' + new Date().toISOString(),
                telephone1: '555-0200',
            });

            crudOutput = `Account updated successfully!\n\nID: ${createdAccountId}\nUpdated fields: description, telephone1\n`;

            await showNotification('Account Updated', 'Account updated successfully', 'success');
            dispatch('log', { message: `Account updated: ${createdAccountId}`, type: 'success' });
        } catch (error) {
            crudOutput = `Error: ${(error as Error).message}`;
            dispatch('log', { message: `Error updating account: ${(error as Error).message}`, type: 'error' });
        }
    }

    async function deleteAccount() {
        if (!createdAccountId) {
            await showNotification('No Account', 'Please create an account first', 'warning');
            return;
        }

        try {
            crudOutput = 'Deleting account...\n';

            await window.dataverseAPI.delete('account', createdAccountId);

            crudOutput = `Account deleted successfully!\n\nID: ${createdAccountId}\n`;

            await showNotification('Account Deleted', 'Account deleted successfully', 'success');
            dispatch('log', { message: `Account deleted: ${createdAccountId}`, type: 'success' });
            createdAccountId = null;
        } catch (error) {
            crudOutput = `Error: ${(error as Error).message}`;
            dispatch('log', { message: `Error deleting account: ${(error as Error).message}`, type: 'error' });
        }
    }

    async function getAccountMetadata() {
        if (!connection) {
            await showNotification('No Connection', 'Please connect to a Dataverse environment', 'warning');
            return;
        }

        try {
            metadataOutput = 'Retrieving metadata...\n';

            const metadata = await window.dataverseAPI.getEntityMetadata('account', true);

            let output = 'Account Entity Metadata:\n\n';
            output += `Logical Name: ${metadata.LogicalName}\n`;
            output += `Metadata ID: ${metadata.MetadataId}\n`;
            output += `Display Name: ${metadata.DisplayName?.LocalizedLabels?.[0]?.Label || 'N/A'}\n`;
            output += `Attributes: ${metadata.Attributes?.length || 0}\n`;

            if (metadata.Attributes && metadata.Attributes.length > 0) {
                output += '\nSample Attributes:\n';
                metadata.Attributes.slice(0, 5).forEach((attr: any) => {
                    output += `  - ${attr.LogicalName} (${attr.AttributeType})\n`;
                });
            }

            metadataOutput = output;
            dispatch('log', { message: 'Account metadata retrieved', type: 'success' });
        } catch (error) {
            metadataOutput = `Error: ${(error as Error).message}`;
            dispatch('log', { message: `Error getting metadata: ${(error as Error).message}`, type: 'error' });
        }
    }
</script>

<div class="card">
    <h2>💾 Dataverse API Examples</h2>

    <div class="example-group">
        <h3>Query Records</h3>
        <button class="btn btn-primary" on:click={queryAccounts}>Query Top 10 Accounts</button>
        <div class="output">{queryOutput}</div>
    </div>

    <div class="example-group">
        <h3>CRUD Operations</h3>
        <div class="input-group">
            <label for="account-name">Account Name:</label>
            <input type="text" id="account-name" bind:value={accountName} placeholder="Enter account name" />
        </div>
        <div class="button-group">
            <button class="btn btn-primary" on:click={createAccount}>Create Account</button>
            <button class="btn" disabled={!createdAccountId} on:click={updateAccount}>Update Account</button>
            <button class="btn btn-error" disabled={!createdAccountId} on:click={deleteAccount}>Delete Account</button>
        </div>
        <div class="output">{crudOutput}</div>
    </div>

    <div class="example-group">
        <h3>Metadata</h3>
        <button class="btn" on:click={getAccountMetadata}>Get Account Metadata</button>
        <div class="output">{metadataOutput}</div>
    </div>
</div>

// generators/app/templates/reactfluent/src/components/DataverseAPIDemo.tsx
import React, { useState, useCallback } from "react";
import {
  Card,
  CardHeader,
  Button,
  Input,
  Text,
  Label,
  makeStyles,
  tokens,
} from "@fluentui/react-components";
import {
  Search24Regular,
  Add24Regular,
  Edit24Regular,
  Delete24Regular,
  Database24Regular,
} from "@fluentui/react-icons";

interface DataverseAPIDemoProps {
  connection: ToolBoxAPI.DataverseConnection | null;
  onLog: (
    message: string,
    type?: "info" | "success" | "warning" | "error"
  ) => void;
}

const useStyles = makeStyles({
  card: {
    maxWidth: "100%",
    width: "100%",
  },
  content: {
    padding: tokens.spacingVerticalM,
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalL,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalS,
  },
  buttonGroup: {
    display: "flex",
    gap: tokens.spacingHorizontalS,
    flexWrap: "wrap",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXS,
    maxWidth: "400px",
  },
  output: {
    fontFamily: tokens.fontFamilyMonospace,
    fontSize: tokens.fontSizeBase200,
    backgroundColor: tokens.colorNeutralBackground3,
    padding: tokens.spacingVerticalM,
    borderRadius: tokens.borderRadiusMedium,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    minHeight: "100px",
    maxHeight: "300px",
    overflowY: "auto",
  },
});

export const DataverseAPIDemo: React.FC<DataverseAPIDemoProps> = ({
  connection,
  onLog,
}) => {
  const styles = useStyles();
  const [accountName, setAccountName] = useState("Sample Account");
  const [createdAccountId, setCreatedAccountId] = useState<string | null>(null);
  const [queryOutput, setQueryOutput] = useState("");
  const [crudOutput, setCrudOutput] = useState("");
  const [metadataOutput, setMetadataOutput] = useState("");

  const showNotification = useCallback(
    async (
      title: string,
      body: string,
      type: "success" | "info" | "warning" | "error"
    ) => {
      try {
        await window.toolboxAPI.utils.showNotification({
          title,
          body,
          type,
          duration: 3000,
        });
      } catch (error) {
        console.error("Error showing notification:", error);
      }
    },
    []
  );

  const queryAccounts = useCallback(async () => {
    if (!connection) {
      await showNotification(
        "No Connection",
        "Please connect to a Dataverse environment",
        "warning"
      );
      return;
    }

    try {
      setQueryOutput("Querying accounts...\n");

      const fetchXml = `
<fetch top="10">
  <entity name="account">
    <attribute name="name" />
    <attribute name="accountid" />
    <attribute name="emailaddress1" />
    <attribute name="telephone1" />
    <order attribute="name" />
  </entity>
</fetch>
            `.trim();

      const result = await window.dataverseAPI.fetchXmlQuery(fetchXml);

      let output = `Found ${result.value.length} account(s):\n\n`;
      result.value.forEach((account: any, index: number) => {
        output += `${index + 1}. ${account.name}\n`;
        output += `   ID: ${account.accountid}\n`;
        if (account.emailaddress1)
          output += `   Email: ${account.emailaddress1}\n`;
        if (account.telephone1) output += `   Phone: ${account.telephone1}\n`;
        output += "\n";
      });

      setQueryOutput(output);
      onLog(`Queried ${result.value.length} accounts`, "success");
    } catch (error) {
      const errorMsg = `Error: ${(error as Error).message}`;
      setQueryOutput(errorMsg);
      onLog(`Error querying accounts: ${(error as Error).message}`, "error");
    }
  }, [connection, onLog, showNotification]);

  const createAccount = useCallback(async () => {
    if (!connection) {
      await showNotification(
        "No Connection",
        "Please connect to a Dataverse environment",
        "warning"
      );
      return;
    }

    try {
      setCrudOutput("Creating account...\n");

      const result = await window.dataverseAPI.create("account", {
        name: accountName,
        emailaddress1: "sample@example.com",
        telephone1: "555-0100",
        description: "Created by React Sample Tool",
      });

      setCreatedAccountId(result.id);

      const output = `Account created successfully!\n\nID: ${result.id}\nName: ${accountName}\n`;
      setCrudOutput(output);

      await showNotification(
        "Account Created",
        `Account "${accountName}" created successfully`,
        "success"
      );
      onLog(`Account created: ${result.id}`, "success");
    } catch (error) {
      const errorMsg = `Error: ${(error as Error).message}`;
      setCrudOutput(errorMsg);
      onLog(`Error creating account: ${(error as Error).message}`, "error");
    }
  }, [connection, accountName, onLog, showNotification]);

  const updateAccount = useCallback(async () => {
    if (!createdAccountId) {
      await showNotification(
        "No Account",
        "Please create an account first",
        "warning"
      );
      return;
    }

    try {
      setCrudOutput("Updating account...\n");

      await window.dataverseAPI.update("account", createdAccountId, {
        description:
          "Updated by React Sample Tool at " + new Date().toISOString(),
        telephone1: "555-0200",
      });

      const output = `Account updated successfully!\n\nID: ${createdAccountId}\nUpdated fields: description, telephone1\n`;
      setCrudOutput(output);

      await showNotification(
        "Account Updated",
        "Account updated successfully",
        "success"
      );
      onLog(`Account updated: ${createdAccountId}`, "success");
    } catch (error) {
      const errorMsg = `Error: ${(error as Error).message}`;
      setCrudOutput(errorMsg);
      onLog(`Error updating account: ${(error as Error).message}`, "error");
    }
  }, [createdAccountId, onLog, showNotification]);

  const deleteAccount = useCallback(async () => {
    if (!createdAccountId) {
      await showNotification(
        "No Account",
        "Please create an account first",
        "warning"
      );
      return;
    }

    try {
      setCrudOutput("Deleting account...\n");

      await window.dataverseAPI.delete("account", createdAccountId);

      const output = `Account deleted successfully!\n\nID: ${createdAccountId}\n`;
      setCrudOutput(output);

      await showNotification(
        "Account Deleted",
        "Account deleted successfully",
        "success"
      );
      onLog(`Account deleted: ${createdAccountId}`, "success");
      setCreatedAccountId(null);
    } catch (error) {
      const errorMsg = `Error: ${(error as Error).message}`;
      setCrudOutput(errorMsg);
      onLog(`Error deleting account: ${(error as Error).message}`, "error");
    }
  }, [createdAccountId, onLog, showNotification]);

  const getAccountMetadata = useCallback(async () => {
    if (!connection) {
      await showNotification(
        "No Connection",
        "Please connect to a Dataverse environment",
        "warning"
      );
      return;
    }

    try {
      setMetadataOutput("Retrieving metadata...\n");

      const metadata = await window.dataverseAPI.getEntityMetadata(
        "account",
        true
      );

      let output = "Account Entity Metadata:\n\n";
      output += `Logical Name: ${metadata.LogicalName}\n`;
      output += `Metadata ID: ${metadata.MetadataId}\n`;
      output += `Display Name: ${
        metadata.DisplayName?.LocalizedLabels?.[0]?.Label || "N/A"
      }\n`;
      output += `Attributes: ${metadata.Attributes?.length || 0}\n`;

      if (metadata.Attributes && metadata.Attributes.length > 0) {
        output += "\nSample Attributes:\n";
        metadata.Attributes.slice(0, 5).forEach((attr: any) => {
          output += `  - ${attr.LogicalName} (${attr.AttributeType})\n`;
        });
      }

      setMetadataOutput(output);
      onLog("Account metadata retrieved", "success");
    } catch (error) {
      const errorMsg = `Error: ${(error as Error).message}`;
      setMetadataOutput(errorMsg);
      onLog(`Error getting metadata: ${(error as Error).message}`, "error");
    }
  }, [connection, onLog, showNotification]);

  return (
    <Card className={styles.card}>
      <CardHeader
        header={
          <Text weight="semibold" size={400}>
            💾 Dataverse API Examples
          </Text>
        }
      />
      <div className={styles.content}>
        <div className={styles.section}>
          <Text weight="semibold">Query Records</Text>
          <Button
            appearance="primary"
            icon={<Search24Regular />}
            onClick={queryAccounts}
          >
            Query Top 10 Accounts
          </Button>
          {queryOutput && <div className={styles.output}>{queryOutput}</div>}
        </div>

        <div className={styles.section}>
          <Text weight="semibold">CRUD Operations</Text>
          <div className={styles.inputGroup}>
            <Label htmlFor="account-name">Account Name:</Label>
            <Input
              id="account-name"
              value={accountName}
              onChange={(_e, data) => setAccountName(data.value)}
              placeholder="Enter account name"
            />
          </div>
          <div className={styles.buttonGroup}>
            <Button
              appearance="primary"
              icon={<Add24Regular />}
              onClick={createAccount}
            >
              Create Account
            </Button>
            <Button
              icon={<Edit24Regular />}
              onClick={updateAccount}
              disabled={!createdAccountId}
            >
              Update Account
            </Button>
            <Button
              appearance="primary"
              icon={<Delete24Regular />}
              onClick={deleteAccount}
              disabled={!createdAccountId}
            >
              Delete Account
            </Button>
          </div>
          {crudOutput && <div className={styles.output}>{crudOutput}</div>}
        </div>

        <div className={styles.section}>
          <Text weight="semibold">Metadata</Text>
          <Button icon={<Database24Regular />} onClick={getAccountMetadata}>
            Get Account Metadata
          </Button>
          {metadataOutput && (
            <div className={styles.output}>{metadataOutput}</div>
          )}
        </div>
      </div>
    </Card>
  );
};
